import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import type { BranchRef, UserProfile, UserRole } from '@/lib/types';
import DataTable from '@/components/DataTable';
import Modal from '@/components/Modal';
import { Loader2, Plus, ToggleLeft, ToggleRight } from 'lucide-react';

export default function AdminUsersPage(){
  const [users,setUsers]=useState<UserProfile[]>([]);const[branches,setBranches]=useState<BranchRef[]>([]);const[loading,setLoading]=useState(true);const[show,setShow]=useState(false);const[saving,setSaving]=useState(false);const[error,setError]=useState('');const[form,setForm]=useState({fullName:'',email:'',password:'',phone:'',role:'cashier' as UserRole,branchId:''});
  const load=async()=>{setLoading(true);try{const[u,b]=await Promise.all([api.get<{data:UserProfile[]}>('/api/admin/users'),api.get<{data:BranchRef[]}>('/api/admin/branches')]);setUsers(u.data);setBranches(b.data)}catch(e){setError(e instanceof Error?e.message:'Failed to load')}finally{setLoading(false)}};useEffect(()=>{load()},[]);
  const save=async()=>{setSaving(true);setError('');try{await api.post('/api/admin/users',{...form,branchId:form.branchId||null});setShow(false);setForm({fullName:'',email:'',password:'',phone:'',role:'cashier',branchId:''});await load()}catch(e){setError(e instanceof Error?e.message:'Create failed')}finally{setSaving(false)}};
  const toggle=async(u:UserProfile)=>{try{await api.patch(`/api/admin/users/${u._id}/status`,{isActive:!u.isActive});await load()}catch(e){setError(e instanceof Error?e.message:'Update failed')}};
  const cols=[{key:'name',label:'User',render:(u:UserProfile)=><div><p className="font-medium">{u.fullName}</p><p className="text-xs text-gray-500">{u.email}</p></div>},{key:'role',label:'Role',render:(u:UserProfile)=><span className="badge-gray capitalize">{u.role}</span>},{key:'branch',label:'Branch',render:(u:UserProfile)=>u.branch?.name??'All / unassigned'},{key:'status',label:'Status',render:(u:UserProfile)=><span className={u.isActive?'badge-success':'badge-danger'}>{u.isActive?'Active':'Disabled'}</span>},{key:'action',label:'',render:(u:UserProfile)=><button className="p-2 rounded hover:bg-gray-100 dark:hover:bg-gray-800" onClick={()=>toggle(u)}>{u.isActive?<ToggleRight className="w-5 h-5 text-green-600"/>:<ToggleLeft className="w-5 h-5"/>}</button>}];
  return <div className="space-y-4"><div className="flex justify-between gap-3"><div><h3 className="font-semibold text-lg">Staff & Access Control</h3><p className="text-sm text-gray-500">Only administrators can create accounts and assign roles.</p></div><button className="btn-primary" onClick={()=>{setError('');setShow(true)}}><Plus className="w-4 h-4"/>Add User</button></div>{error&&<div className="p-3 bg-red-50 text-red-600 rounded-lg">{error}</div>}<div className="card">{loading?<div className="py-16 grid place-items-center"><Loader2 className="w-8 h-8 animate-spin text-primary-600"/></div>:<DataTable data={users.map(u=>({...u,id:u._id}))} columns={cols as any} pageSize={20}/>}</div>
  <Modal isOpen={show} onClose={()=>setShow(false)} title="Create Staff Account"><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><F l="Full Name"><input className="input" value={form.fullName} onChange={e=>setForm({...form,fullName:e.target.value})}/></F><F l="Email"><input type="email" className="input" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></F><F l="Password"><input type="password" minLength={8} className="input" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></F><F l="Phone"><input className="input" value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})}/></F><F l="Role"><select className="input" value={form.role} onChange={e=>setForm({...form,role:e.target.value as UserRole})}><option value="admin">Admin</option><option value="manager">Manager</option><option value="pharmacist">Pharmacist</option><option value="cashier">Cashier</option><option value="inventory">Inventory</option></select></F><F l="Branch"><select className="input" value={form.branchId} onChange={e=>setForm({...form,branchId:e.target.value})}><option value="">Unassigned / all branches</option>{branches.map(b=><option key={b._id} value={b._id}>{b.name}</option>)}</select></F></div>{error&&<div className="mt-4 p-3 bg-red-50 text-red-600 rounded-lg">{error}</div>}<div className="flex justify-end gap-2 mt-6"><button className="btn-secondary" onClick={()=>setShow(false)}>Cancel</button><button className="btn-primary" onClick={save} disabled={saving||!form.fullName||!form.email||form.password.length<8}>{saving&&<Loader2 className="w-4 h-4 animate-spin"/>}Create User</button></div></Modal></div>
}
function F({l,children}:{l:string;children:React.ReactNode}){return <div><label className="label">{l}</label>{children}</div>}
