import { useCallback, useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import type { CatalogMedicine, Sale } from '@/lib/types';
import { formatCurrency, formatDate } from '@/lib/utils';
import Modal from '@/components/Modal';
import { Banknote, CreditCard, Loader2, Minus, Plus, Printer, QrCode, Search, ShoppingCart, Smartphone, Trash2, UserPlus } from 'lucide-react';

type Unit='unit'|'strip'|'box';
interface Customer { _id:string; name:string; phone?:string; balance:number }
interface CartItem { medicine:CatalogMedicine; unit:Unit; quantity:number }
const payments=[{id:'cash',label:'Cash',icon:<Banknote className="w-4 h-4"/>},{id:'card',label:'Card',icon:<CreditCard className="w-4 h-4"/>},{id:'bkash',label:'bKash',icon:<Smartphone className="w-4 h-4"/>},{id:'nagad',label:'Nagad',icon:<Smartphone className="w-4 h-4"/>},{id:'bangla_qr',label:'Bangla QR',icon:<QrCode className="w-4 h-4"/>},{id:'due',label:'Due',icon:<Banknote className="w-4 h-4"/>}];
function multiplier(m:CatalogMedicine,u:Unit){return u==='box'?m.stripsPerBox*m.unitsPerStrip:u==='strip'?m.unitsPerStrip:1}
function unitPrice(m:CatalogMedicine,u:Unit){return m.sellingPrice*multiplier(m,u)}

export default function POSPage(){
  const [catalog,setCatalog]=useState<CatalogMedicine[]>([]); const [customers,setCustomers]=useState<Customer[]>([]); const [search,setSearch]=useState(''); const [cart,setCart]=useState<CartItem[]>([]); const [customerId,setCustomerId]=useState(''); const [paymentMethod,setPaymentMethod]=useState('cash'); const [discount,setDiscount]=useState(0); const [paidAmount,setPaidAmount]=useState(0); const [notes,setNotes]=useState(''); const [loading,setLoading]=useState(true); const [processing,setProcessing]=useState(false); const [error,setError]=useState(''); const [lastSale,setLastSale]=useState<Sale|null>(null); const [showCustomer,setShowCustomer]=useState(false); const [newCustomer,setNewCustomer]=useState({name:'',phone:''});
  const load=useCallback(async()=>{setLoading(true);try{const [c,cu]=await Promise.all([api.get<{data:CatalogMedicine[]}>('/api/sales/catalog'),api.get<{data:Customer[]}>('/api/sales/customers')]);setCatalog(c.data);setCustomers(cu.data)}catch(e){setError(e instanceof Error?e.message:'Failed to load POS')}finally{setLoading(false)}},[]);
  useEffect(()=>{load()},[load]);
  const shown=useMemo(()=>{const q=search.toLowerCase().trim();return catalog.filter(m=>!q||`${m.brandName} ${m.genericName} ${m.sku||''} ${m.barcode||''}`.toLowerCase().includes(q)).slice(0,40)},[catalog,search]);
  const subtotal=cart.reduce((s,c)=>s+unitPrice(c.medicine,c.unit)*c.quantity,0); const total=Math.max(0,subtotal-discount);
  useEffect(()=>{if(paymentMethod!=='due')setPaidAmount(total); else setPaidAmount(0)},[total,paymentMethod]);
  const add=(m:CatalogMedicine)=>{setCart(prev=>{const found=prev.find(c=>c.medicine._id===m._id&&c.unit==='unit');if(found)return prev.map(c=>c===found?{...c,quantity:c.quantity+1}:c);return[...prev,{medicine:m,unit:'unit',quantity:1}]})};
  const update=(i:number,patch:Partial<CartItem>)=>setCart(prev=>prev.map((c,idx)=>idx===i?{...c,...patch}:c));
  const remove=(i:number)=>setCart(prev=>prev.filter((_,idx)=>idx!==i));
  const checkout=async()=>{if(cart.length===0)return;setProcessing(true);setError('');try{const result=await api.post<{data:Sale}>('/api/sales',{customerId:customerId||null,items:cart.map(c=>({medicineId:c.medicine._id,unit:c.unit,quantity:c.quantity})),discount,paymentMethod,paidAmount,notes});setLastSale(result.data);setCart([]);setDiscount(0);setNotes('');setCustomerId('');setPaymentMethod('cash');await load()}catch(e){setError(e instanceof Error?e.message:'Sale failed')}finally{setProcessing(false)}};
  const createCustomer=async()=>{try{const r=await api.post<{data:Customer}>('/api/sales/customers',newCustomer);setCustomers(p=>[r.data,...p]);setCustomerId(r.data._id);setShowCustomer(false);setNewCustomer({name:'',phone:''})}catch(e){setError(e instanceof Error?e.message:'Customer creation failed')}};
  return <div className="grid grid-cols-1 xl:grid-cols-[1fr_440px] gap-5">
    <section className="space-y-4">
      <div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-5 h-5 text-gray-400"/><input autoFocus className="input pl-11 text-base py-3" placeholder="Scan barcode or search brand, generic, SKU..." value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){const exact=catalog.find(m=>m.barcode===search.trim()||m.sku?.toLowerCase()===search.trim().toLowerCase());const target=exact??(shown.length===1?shown[0]:null);if(target){e.preventDefault();add(target);setSearch('')}}}}/></div>
      {error&&<div className="p-3 rounded-lg bg-red-50 dark:bg-red-900/20 text-red-600">{error}</div>}
      {loading?<div className="py-20 grid place-items-center"><Loader2 className="w-8 h-8 animate-spin text-primary-600"/></div>:<div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-3">{shown.map(m=><button key={m._id} onClick={()=>add(m)} className="card p-4 text-left hover:border-primary-400 hover:shadow-md transition-all"><div className="flex justify-between gap-3"><div><p className="font-semibold">{m.brandName} {m.strength}</p><p className="text-xs text-gray-500 mt-0.5">{m.genericName}</p></div><span className="font-semibold text-primary-600">{formatCurrency(m.sellingPrice)}</span></div><div className="flex justify-between mt-4 text-xs text-gray-500"><span>Stock: {m.stock}</span><span>Exp: {formatDate(m.nearestExpiry)}</span></div></button>)}</div>}
    </section>
    <aside className="card h-fit xl:sticky xl:top-20 overflow-hidden"><div className="p-4 border-b flex justify-between items-center"><div className="flex items-center gap-2"><ShoppingCart className="w-5 h-5"/><h3 className="font-semibold">Current Sale</h3></div><span className="badge-gray">{cart.length} items</span></div>
      <div className="p-4 border-b space-y-3 max-h-[44vh] overflow-auto">{cart.length===0?<p className="text-center text-gray-400 py-10">Add medicines to start a sale.</p>:cart.map((c,i)=><div key={`${c.medicine._id}-${i}`} className="rounded-lg border p-3"><div className="flex justify-between gap-2"><div><p className="font-medium text-sm">{c.medicine.brandName} {c.medicine.strength}</p><p className="text-xs text-gray-500">{c.medicine.genericName}</p></div><button onClick={()=>remove(i)} className="text-gray-400 hover:text-red-600"><Trash2 className="w-4 h-4"/></button></div><div className="grid grid-cols-[1fr_auto] gap-2 mt-3"><select className="input py-1.5" value={c.unit} onChange={e=>update(i,{unit:e.target.value as Unit})}><option value="unit">Unit</option>{c.medicine.unitsPerStrip>1&&<option value="strip">Strip ({c.medicine.unitsPerStrip})</option>}{c.medicine.stripsPerBox>1&&<option value="box">Box ({c.medicine.stripsPerBox} strips)</option>}</select><div className="flex items-center border rounded-lg"><button className="p-2" onClick={()=>update(i,{quantity:Math.max(1,c.quantity-1)})}><Minus className="w-3 h-3"/></button><input className="w-12 text-center bg-transparent text-sm outline-none" type="number" min="1" value={c.quantity} onChange={e=>update(i,{quantity:Math.max(1,Number(e.target.value)||1)})}/><button className="p-2" onClick={()=>update(i,{quantity:c.quantity+1})}><Plus className="w-3 h-3"/></button></div></div><div className="flex justify-between mt-2 text-sm"><span>{formatCurrency(unitPrice(c.medicine,c.unit))} × {c.quantity}</span><span className="font-semibold">{formatCurrency(unitPrice(c.medicine,c.unit)*c.quantity)}</span></div></div>)}</div>
      <div className="p-4 space-y-3">
        <div className="flex gap-2"><select className="input" value={customerId} onChange={e=>setCustomerId(e.target.value)}><option value="">Walk-in customer</option>{customers.map(c=><option key={c._id} value={c._id}>{c.name}{c.phone?` · ${c.phone}`:''}</option>)}</select><button className="btn-secondary px-3" onClick={()=>setShowCustomer(true)} title="Quick add customer"><UserPlus className="w-4 h-4"/></button></div>
        <div className="grid grid-cols-2 gap-2"><div><label className="label">Discount</label><input type="number" min="0" max={subtotal} step="0.01" className="input" value={discount} onChange={e=>setDiscount(Math.max(0,Number(e.target.value)||0))}/></div><div><label className="label">Paid</label><input type="number" min="0" step="0.01" className="input" value={paidAmount} onChange={e=>setPaidAmount(Math.max(0,Number(e.target.value)||0))}/></div></div>
        <div className="grid grid-cols-3 gap-2">{payments.map(p=><button key={p.id} onClick={()=>setPaymentMethod(p.id)} className={`px-2 py-2 rounded-lg border text-xs flex flex-col items-center gap-1 ${paymentMethod===p.id?'border-primary-500 bg-primary-50 text-primary-700 dark:bg-primary-900/20':'hover:bg-gray-50 dark:hover:bg-gray-800'}`}>{p.icon}{p.label}</button>)}</div>
        <textarea className="input min-h-16" placeholder="Sale note (optional)" value={notes} onChange={e=>setNotes(e.target.value)}/>
        <div className="border-t pt-3 space-y-1 text-sm"><div className="flex justify-between"><span className="text-gray-500">Subtotal</span><span>{formatCurrency(subtotal)}</span></div><div className="flex justify-between"><span className="text-gray-500">Discount</span><span>- {formatCurrency(discount)}</span></div><div className="flex justify-between text-lg font-bold pt-2"><span>Total</span><span>{formatCurrency(total)}</span></div></div>
        <button className="btn-primary w-full py-3" disabled={cart.length===0||processing||(paymentMethod==='due'&&!customerId)} onClick={checkout}>{processing?<Loader2 className="w-4 h-4 animate-spin"/>:<ShoppingCart className="w-4 h-4"/>}Complete Sale</button>{paymentMethod==='due'&&!customerId&&<p className="text-xs text-red-500 text-center">Select a customer for due sales.</p>}
      </div>
    </aside>
    <Modal isOpen={!!lastSale} onClose={()=>setLastSale(null)} title="Sale Completed"><div className="text-center"><div className="w-14 h-14 rounded-full bg-green-100 text-green-600 grid place-items-center mx-auto"><ShoppingCart className="w-7 h-7"/></div><h3 className="text-xl font-bold mt-3">{lastSale?.invoiceNumber}</h3><p className="text-gray-500 mt-1">Total {formatCurrency(lastSale?.total||0)}</p>{(lastSale?.changeAmount||0)>0&&<p className="text-sm text-green-600 font-medium">Change {formatCurrency(lastSale?.changeAmount||0)}</p>}<p className="text-sm text-gray-500">Gross profit {formatCurrency(lastSale?.grossProfit||0)}</p><button onClick={()=>window.print()} className="btn-secondary mt-5"><Printer className="w-4 h-4"/>Print Receipt</button></div></Modal>
    {lastSale&&<div className="print-receipt"><h1>PharmaPOS</h1><p>{lastSale.invoiceNumber}</p><p>{new Date(lastSale.saleDate).toLocaleString()}</p><hr/>{lastSale.items.map((i,idx)=><div key={idx} className="print-line"><span>{i.medicineName} · {i.saleUnitQuantity} {i.saleUnit}</span><span>{formatCurrency(i.lineTotal)}</span></div>)}<hr/><div className="print-line"><strong>Total</strong><strong>{formatCurrency(lastSale.total)}</strong></div><div className="print-line"><span>Paid</span><span>{formatCurrency(lastSale.paidAmount)}</span></div>{(lastSale.changeAmount||0)>0&&<div className="print-line"><span>Change</span><span>{formatCurrency(lastSale.changeAmount||0)}</span></div>}<p className="print-thanks">Thank you</p></div>}
    <Modal isOpen={showCustomer} onClose={()=>setShowCustomer(false)} title="Quick Add Customer"><div className="space-y-4"><div><label className="label">Name</label><input className="input" value={newCustomer.name} onChange={e=>setNewCustomer({...newCustomer,name:e.target.value})}/></div><div><label className="label">Phone</label><input className="input" value={newCustomer.phone} onChange={e=>setNewCustomer({...newCustomer,phone:e.target.value})}/></div><div className="flex justify-end gap-2"><button className="btn-secondary" onClick={()=>setShowCustomer(false)}>Cancel</button><button className="btn-primary" disabled={newCustomer.name.trim().length<2} onClick={createCustomer}>Save Customer</button></div></div></Modal>
  </div>
}
